### PR TITLE
add AlwaysBreakAfterReturnType to all_settings variable

### PR DESCRIPTION
**Pull request by rapimo**
AlwaysBreakAfterDefinitionReturnType is deprecated
this adds AlwaysBreakAfterReturnType 
https://clang.llvm.org/docs/ClangFormatStyleOptions.html

### CODE REVIEW

**Comment by rapimo** [comment]
I didn't put it into `clang_format_custom.sublime-settings` to avoid problems with older versions of ClangFormat

**Comment by rapimo** [comment]
I added your suggested change to clang_format_custom.sublime-settings.
However I did not receive an invite for collaboration so I can't merge it on my own.

**Comment by rapimo** [comment]
any news here?

**Comment by rosshemsley** [comment]
Thanks @rapimo!

**Pull request merged**
