### PR TITLE
Format whole file if nothing selected

### PR DESCRIPTION
**Pull request by junzh0u**
As title says.

### CODE REVIEW

**Comment by justbuchanan** [comment]
+1 For this feature, it would be really helpful!

**Comment by vilhelmen** [comment]
I guess I'm a little late to the party, but it would be a nice addition. But I suppose passing an argument works. Maybe add that to the readme for others who don't find this?

**Comment by temoto** [comment]
:+1: 
Please, make it non-default option, make it only configurable at certain time of day, make me eat a bag of shit to enable this great option. But please, make it a bit lesser bag than installing Sublime-2 targeted ProjectSpecific to enable format_on_save.

**Comment by temoto** [comment]
For those who just want whole file formatted on every save, I've created pull request #30 it works on Sublime 3. To patch existing installation, find Clang Format.sublime-package, unzip, modify clang_format.py, zip back.

**Comment by leondmello** [comment]
👍 lgtm

**Comment by rapimo** [comment]
closed by #30

**Pull request closed without merging**
